=== inab/benchmarking-data-model/json-schemas/2.0.x/challenge.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/Challenge",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Challenge concept (OpenEBench Benchmarking Data Model schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares __canonical_id__, _metadata, __revision__, __license__",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of orig_id",
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$comment": "Declaration of references",
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$comment": "Declaration of links",
			"$ref": "_shared#/definitions/LinksProp"
		},
		{
			"$comment": "Declarations of name, description",
			"$ref": "_shared#/definitions/NameDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the challenge, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/ChallengeTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/ChallengeId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of '$id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/Challenge" ]
		},
		
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The challenge original id"
		},
		
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The challenge reference id(s) (if any)"
		},
		
		"links": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksProp",
			"title": "Ways to contact the challenge responsible. It can be many different ones: public page, a social media link, some public chat, a public mailing list, ..."
		},
		
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Short challenge name"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Long challenge description, written in Markdown"
		},
		"keywords": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "List of keywords which match this challenge"
		},
		
		"acronym": {
			"title": "Friendly challenge acronym",
			"minLength": 1,
			"type": "string"
		},
		"benchmarking_event_id": {
			"title": "The parent benchmarking event",
			"minLength": 1,
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "BenchmarkingEvent",
					"members": [ "." ]
				}
			]
		},
		"is_automated": {
			"title": "Is this an automated challenge?",
			"type": "boolean"
		},
		"participation_model": {
			"title": "Challenge participation model",
			"description": "There are four main models, which can be combined with individual dataset and test action anonimization level: public, where all the participant results are visible just when they are uploaded; anonymous: the results of the participants are public, but they are anonymous until the end of the challenge; embargoed: the results of the participants are under controlled access with no anonymization; secret: the results of the participants are under controlled access, and they remain anonymized until the end of the challenge",
			"type": "string",
			"enum": [
				"public",
				"anonymous",
				"embargoed",
				"secret"
			]
		},
		"dates": {
			"title": "Relevant dates for this challenge",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the challenge",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the challenge",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this challenge becomes public",
					"type": "string",
					"format": "date-time"
				},
				"challenge_start": {
					"title": "When starts the challenge?",
					"type": "string",
					"format": "date-time"
				},
				"challenge_stop": {
					"title": "When stops the challenge?",
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false,
			"required": ["creation","modification"],
			"dependencies": {
				"challenge_start": ["challenge_stop"],
				"challenge_stop": ["challenge_start"]
			}
		},
		"metrics": {
			"title": "The list of available metrics in this category",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"metrics_id": {
						"title": "The metrics id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Metrics",
								"members": [ "." ]
							}
						]
					},
					"tool_id": {
						"title": "The optional tool id which computes this metric(s)",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Tool",
								"members": [ "." ]
							}
						]
					}
				},
				"index": {
					"members": [
						"metrics_id"
					],
					"name": "MetricsAssessmentIndex",
					"limit_scope": true
				},
				"additionalProperties": false,
				"required": [ "metrics_id", "tool_id" ]
			}
		},
		"representations": {
			"title": "The list of available representations (ways to combine metrics) for the aggregation. When this tag is not available, no associated aggregation dataset should exist",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"representation_id": {
						"title": "The representation id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Representation",
								"members": [ "." ]
							}
						]
					},
					"tool_id": {
						"title": "The optional tool id which computes this metric(s)",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Tool",
								"members": [ "." ]
							}
						]
					},
					"metrics_combinations": {
						"title": "The allowed metrics combinations. If absent, any metrics combination is allowed. If present, only the combinations declare here are valid",
						"type": "array",
						"minItems": 1,
						"items": {
							"type": "array",
							"minItems": 1,
							"items": {
								"title": "The allowed metrics id",
								"type": "string",
								"join_keys": [
									{
										"members": ["."],
										"refers_to": "MetricsAssessmentIndex"
									}
								]
							}
						}
					}
				},
				"additionalProperties": false,
				"required": [ "representation_id", "tool_id" ]
			}
		},
		"challenge_contact_ids": {
			"title": "The challenge contact id(s)",
			"$ref": "_shared#/definitions/ReferredContactIds"
		}
	},
	"unevaluatedProperties": false,
	"required": [
		"_id",
		"_schema",
		"name",
		"benchmarking_event_id",
		"is_automated",
		"participation_model",
		"dates",
		"challenge_contact_ids",
		"metrics"
	],
	
	"primary_key": ["_id"],
	"index": [
		{
			"members": [
				"_id",
				"metrics.metrics_id"
			],
			"name": "MetricsChallengeIndex",
			"limit_scope": true
		},
		{
			"members": [
				"_id",
				"representations.representation_id"
			],
			"name": "RepresentationChallengeIndex",
			"limit_scope": true
		}
	],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/Challenges/Challenge_KIRC_OEBX002t00000C.json
{
    "_id": "TCGA:2018-04-05_KIRC",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Challenge",
    "acronym": "KIRC",
    "benchmarking_event_id": "TCGA:2018-04-05",
    "challenge_contact_ids": [
        "orcid:0000-0003-4526-9727",
        "orcid:0000-0001-7900-4239",
        "orcid:0000-0003-1395-5378"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z",
        "challenge_start": "2018-04-05T05:00:00Z",
        "challenge_stop": "2018-04-05T02:00:00Z"
    },
    "is_automated": false,
    "metrics": [
        {
            "metrics_id": "TCGA:TPR",
            "tool_id": "TCGA:compute_TPR"
        },
        {
            "metrics_id": "TCGA:precision",
            "tool_id": "TCGA:compute_precision"
        }
    ],
    "representations": [
        {
            "representation_id": "TCGA:aggregation",
            "tool_id": "TCGA:aggregate_benchmark"
        }
    ],
    "name": "Cancer Driver Genes Prediction Benchmark in Kidney Renal Clear Cell Carcinoma",
    "references": [
        "doi:10.1016/j.cell.2018.02.060"
    ],
    "links": [
        {
            "label": "MainSite",
            "uri": "https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers/renal-cell-clear-cell"
        }
    ],
    "participation_model": "anonymous"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/Challenges/Challenge_SKCM_OEBX002t00000Q.json
{
    "_id": "TCGA:2018-04-05_SKCM",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Challenge",
    "acronym": "SKCM",
    "benchmarking_event_id": "TCGA:2018-04-05",
    "challenge_contact_ids": [
        "orcid:0000-0003-4526-9727",
        "orcid:0000-0001-7900-4239",
        "orcid:0000-0003-1395-5378"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z",
        "challenge_start": "2018-04-05T05:00:00Z",
        "challenge_stop": "2018-04-05T02:00:00Z"
    },
    "is_automated": false,
    "metrics": [
        {
            "metrics_id": "TCGA:TPR",
            "tool_id": "TCGA:compute_TPR"
        },
        {
            "metrics_id": "TCGA:precision",
            "tool_id": "TCGA:compute_precision"
        }
    ],
    "representations": [
        {
            "representation_id": "TCGA:aggregation",
            "tool_id": "TCGA:aggregate_benchmark"
        }
    ],
    "name": "Cancer Driver Genes Prediction Benchmark in Skin Cutaneous Melanoma",
    "references": [
        "doi:10.1016/j.cell.2018.02.060"
    ],
    "links": [
        {
            "label": "MainSite",
            "uri": "https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers/melanoma-skin"
        }
    ],
    "participation_model": "anonymous"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/Challenges/Challenge_ALL_OEBX002t00000Y.json
{
    "_id": "TCGA:2018-04-05_ALL",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Challenge",
    "acronym": "ALL",
    "benchmarking_event_id": "TCGA:2018-04-05",
    "challenge_contact_ids": [
        "orcid:0000-0003-4526-9727",
        "orcid:0000-0001-7900-4239",
        "orcid:0000-0003-1395-5378"
    ],
    "dates": {
        "creation": "2018-04-05T00:00:00Z",
        "modification": "2018-04-05T14:00:00Z",
        "challenge_start": "2018-04-05T05:00:00Z",
        "challenge_stop": "2018-04-05T02:00:00Z"
    },
    "is_automated": false,
    "metrics": [
        {
            "metrics_id": "TCGA:TPR",
            "tool_id": "TCGA:compute_TPR"
        },
        {
            "metrics_id": "TCGA:precision",
            "tool_id": "TCGA:compute_precision"
        }
    ],
    "representations": [
        {
            "representation_id": "TCGA:aggregation",
            "tool_id": "TCGA:aggregate_benchmark"
        }
    ],
    "name": "Cancer Driver Genes Prediction Benchmark in All cancer types",
    "references": [
        "doi:10.1016/j.cell.2018.02.060"
    ],
    "links": [
        {
            "label": "MainSite",
            "uri": "https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers"
        }
    ],
    "participation_model": "anonymous"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Challenges/Challenge_STD_Fungi.json
{
    "_id": "QfO:2011-07-07_STD_Fungi",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Challenge",
    "acronym": "STD_Fungi",
    "benchmarking_event_id": "OEBE0020000000",
    "challenge_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "dates": {
        "challenge_start": "2011-07-07T00:00:00Z",
        "challenge_stop": "2011-07-07T00:00:00Z",
        "creation": "2011-07-07T00:00:00Z",
        "modification": "2011-07-07T00:00:00Z"
    },
    "is_automated": true,
    "participation_model": "public",
    "metrics": [
        {
            "metrics_id": "QfO:STD_comp_trees",
            "tool_id": "QfO:metrics_computator"
        },
        {
            "metrics_id": "QfO:STD_num_orthologs",
            "tool_id": "QfO:metrics_computator"
        },
        {
            "metrics_id": "QfO:STD_RF_distance",
            "tool_id": "QfO:metrics_computator"
        },
        {
            "metrics_id": "QfO:STD_incorrect_trees",
            "tool_id": "QfO:metrics_computator"
        }
    ],
    "representations": [
        {
            "representation_id": "QfO:aggregation",
            "tool_id": "QfO:aggregate_benchmark"
        }
    ],
    "name": "Species Tree Discordance in Fungi benchmark",
    "references": [
        "doi:10.1093/bib/bbr034"
    ],
    "links": [
        {
            "label": "MainSite",
            "uri": "https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2"
        }
    ]
}
