=== inab/benchmarking-data-model/json-schemas/2.0.x/dataset.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Dataset concept (OpenEBench Benchmarking Data Model schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares __canonical_id__, _metadata, __revision__, __license__",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of orig_id",
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$comment": "Declaration of anonymize",
			"$ref": "_shared#/definitions/AnonymizeProp"
		},
		{
			"$comment": "Declaration of references",
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$comment": "Declarations of name, description",
			"$ref": "_shared#/definitions/NameDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the dataset, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/DatasetTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/DatasetId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of '$id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/Dataset" ]
		},
		
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The dataset original id"
		},
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The reference id(s) of this dataset (if any)"
		},
		
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Short dataset name"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Long dataset description, written in Markdown"
		},
		"keywords": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "List of keywords which match this dataset"
		},
		
		"community_ids": {
			"title": "The communities where this dataset was generated or used",
			"description": "This field is redundant, as it can be obtained from the challenges",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Community",
						"members": [ "." ]
					}
				]
			}
		},
		"challenge_ids": {
			"title": "The challenge(s) where this dataset was generated or used",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Challenge",
						"members": [ "." ]
					}
				],
				"minLength": 1
			}
		},
		"visibility": {
			"title": "The visibility of this dataset, which must be acknowledged by the APIs",
			"type": "string",
			"enum": [ "anonymous", "public", "community", "challenge" ]
		},
		"anonymize": {
			"$comment": "Placeholder covered by _shared#/definitions/AnonymizeProp",
			"title": "Anonymize rule"
		},
		"version": {
			"title": "Version (or relelase date) of the dataset",
			"minLength": 1,
			"type": "string"
		},
		"dates": {
			"title": "Relevant dates for this dataset",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the dataset (from the perspective of the community)",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the dataset (from the perspective of the community)",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this dataset becomes public (honoured when challenges are either 'embargoed' or 'anonymous')",
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false,
			"required": ["creation","modification"]
		},
		"type": {
			"title": "Type of dataset. Aggregation datasets are combinations of other aggregations or assessments.",
			"type": "string",
			"mingLength": 1,
			"enum": [ "public_reference", "metrics_reference", "input", "participant", "assessment", "participant_assessments", "aggregation", "other" ]
		},
		"datalinks": {
			"title": "The data itself, either linked or embedded, and mirrors to it",
			"type": "array",
			"minItems": 1,
			"oneOf": [
				{
					"title": "Inline, embedded data",
					"items": [
						{
							"properties": {
								"inline_data": {
									"title": "Inline data in JSON format",
									"type": "object",
									"minProperties": 1,
									"additionalProperties": true
								},
								"schema_url": {
									"title": "The optional URL to the JSON Schema which validates the inline data. It could be embedded, using the 'data:' protocol encoding",
									"type": "string",
									"pattern": "^(?:http|https|data):.*$",
									"format": "uri"
								}
							},
							"additionalProperties": false,
							"required": [ "inline_data" ]
						}
					],
					"additionalItems": {
						"$ref": "#/$defs/DataLink"
					}
				},
				{
					"title": "The link to reach the dataset",
					"items": {
						"$ref": "#/$defs/DataLink"
					}
				}
			]
		},
		"dataset_contact_ids": {
			"title": "The contact id(s) of the depositor(s)/creator(s) of this dataset",
			"$ref": "_shared#/definitions/ReferredContactIds"
		},
		"participant_team_id": {
			"title": "Participant team which submitted this dataset",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "ParticipantTeam",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"depends_on": {
			"title": "The causal, direct dependencies of this dataset on a tool and other datasets, if available",
			"type": "object",
			"properties": {
				"metrics_id": {
					"title": "The id of the metrics tied to the tool id",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Metrics",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"representation_id": {
					"title": "The id of the metrics tied to the tool id",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Representation",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"tool_id": {
					"title": "The id of the tool which generated this dataset",
					"type": "string",
					"foreign_keys": [
						{
							"schema_id": "Tool",
							"members": [ "." ]
						}
					],
					"minLength": 1
				},
				"rel_dataset_ids": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"dataset_id": {
								"title": "The id of a dataset which was used to generate this new dataset",
								"type": "string",
								"foreign_keys": [
									{
										"schema_id": "Dataset",
										"members": [ "." ]
									}
								],
								"minLength": 1
							},
							"role": {
								"title": "The role of the referenced dataset generating the current one (used to generate the current dataset, superseded by the generated dataset, ....)",
								"type": "string",
								"enum": [ "dependency", "superseded", "report" ],
								"default": "dependency"
							}
						},
						"additionalProperties": false,
						"required": [ "dataset_id" ]
					}
				}
			},
			"additionalProperties": false,
			"join_keys": [
				{
					"schema_id": "Challenge",
					"members": ["_id", "depends_on.metrics_id"],
					"refers_to": "MetricsChallengeIndex"
				},
				{
					"schema_id": "Challenge",
					"members": ["_id", "depends_on.representation_id"],
					"refers_to": "RepresentationChallengeIndex"
				}
			],
			"anyOf": [
				{
					"required": [ "rel_dataset_ids" ]
				},
				{
					"required": [ "tool_id" ]
				},
				{
					"oneOf": [
						{
							"required": [ "metrics_id" ]
						},
						{
							"required": [ "representation_id" ]
						}
					]
				}
			]
		}
	},
	"$defs": {
		"DataLink": {
			"title": "The link to reach the dataset",
			"properties": {
				"uri": {
					"title": "Either inline, encoded data URI; or an official CURIE; or download link to the dataset itself, like an FTP directory or archive, an S3 bucket, a WebDAV directory, an HTTP REST link, etc...; or a link to a Metalink describing the dataset; or a link to a MD5/SHA1 sums file with relative paths",
					"type": "string",
					"format": "uri"
				},
				"schema_uri": {
					"title": "The optional URI to the JSON Schema which validates the remote data, in case it is either JSON or YAML",
					"type": "string",
					"format": "uri"
				},
				"licenses": {
					"title": "The list of associated licenses to the dataset described by this entry",
					"type": "array",
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"$ref": "_shared#/definitions/License"
					}
				},
				"attrs": {
					"title": "Attributes describing the datalink: whether it is inline (i.e. a data URI); a CURIE; whether it is compressed, or an archive (tar, zip, rar), a metalink (RFC 5854, RFC 6249, https://en.wikipedia.org/wiki/Metalink) or a standard sums (MD5, SHA1) file",
					"type": "array",
					"minItems": 1,
					"uniqueItems": true,
					"anyOf": [
						{
							"items": {
								"type": "string",
								"enum": [ "inline","compressed", "archive", "metalink", "sums" ]
							}
						},
						{
							"items": {
								"type": "string",
								"enum": [ "curie", "compressed", "archive", "metalink" ]
							}
						}
					]
				},
				"kind": {
					"documentation": "Nature of the pointed resource. It can be the authoritative (primary) source, a mirror, or a permanent fixed URI, like Zenodo, B2DROP or similar",
					"type": "string",
					"enum": [ "mirror", "authoritative", "pid" ]
				},
				"validations": {
					"title": "Validations performed over the link pointing over the physical dataset. The logs of these validations are stored here.",
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object",
						"properties": {
							"validation_stamp": {
								"title": "Last validation date of the datalink",
								"type": "string",
								"format": "date-time"
							},
							"status": {
								"title": "Last validation status (unreachable content, missing content(404), interrupted while validating, corrupted (checksums, not all the contents available, etc...), ok) or the HTTP code (numerical)",
								"type": "string",
								"oneOf": [
									{
										"type": "string",
										"enum": [ "unreachable", "missing", "interrupted", "corrupted", "ok" ]
									},
									{
										"type": "integer",
										"minimum": 100,
										"exclusiveMaximum": 600
									}
								]
							}
						},
						"required": [
							"validation_stamp",
							"status"
						]
					}
				}
			},
			"additionalProperties": false,
			"required": [ "uri", "attrs" ]
		}
	},
	"oneOf": [
		{
			"$comment": "Participant team id is required for this kind of datasets",
			"properties": {
				"type": {
					"type": "string",
					"const": "participant"
				},
				"community_ids": {
					"description": "There can be only a single community id (if declared) associated to a participant dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"depends_on": {
					"required": ["rel_dataset_ids"],
					"not": {
						"required": ["metrics_id", "representation_id"]
					}
				}
			},
			"required": ["type", "participant_team_id", "depends_on"]
		},
		{
			"properties": {
				"type": {
					"type": "string",
					"const": "assessment"
				},
				"challenge_ids": {
					"description": "There can be only a single challenge id associated to an assessment dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"community_ids": {
					"description": "There can be only a single community id (if declared) associated to an assessment dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"depends_on": {
					"required": ["rel_dataset_ids","metrics_id"],
					"not": {
						"required": ["representation_id"]
					}
				}
			},
			"required": ["type", "challenge_ids", "depends_on"]
		},
		{
			"properties": {
				"type": {
					"type": "string",
					"const": "aggregation"
				},
				"challenge_ids": {
					"description": "There can be only a single challenge id associated to an aggregation dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"community_ids": {
					"description": "There can be only a single community id (if declared) associated to an aggregation dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"depends_on": {
					"required": ["rel_dataset_ids","representation_id"],
					"not": {
						"required": ["metrics_id"]
					}
				}
			},
			"required": ["type", "challenge_ids", "depends_on"]
		},
		{
			"properties": {
				"type": {
					"type": "string",
					"const": "participant_assessments"
				},
				"community_ids": {
					"description": "There can be only a single community id (if declared) associated to a participant assessments dataset",
					"type": "array",
					"minItems": 1,
					"maxItems": 1
				},
				"depends_on": {
					"required": ["rel_dataset_ids","representation_id"],
					"not": {
						"required": ["metrics_id"]
					}
				}
			},
			"required": ["type", "challenge_ids", "depends_on"]
		},
		{
			"$comment": "No participant team id should be allowed for these kinds of datasets",
			"properties": {
				"type": {
					"type": "string",
					"enum": [ "public_reference", "metrics_reference", "input", "other" ]
				},
				"depends_on": {
					"not": {
						"required": ["metrics_id", "representation_id"]
					}
				}
			},
			"not": {
				"required": ["participant_team_id"]
			}
		}
	],
	"unevaluatedProperties": false,
	"required": [
		"_id",
		"_schema",
		"challenge_ids",
		"visibility",
		"name",
		"version",
		"type",
		"dates",
		"datalinks",
		"dataset_contact_ids"
	],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_LUSC_MuSiC_OEBD002t000040.json
{
  "_id": "TCGA:2018-04-05_LUSC_P_MuSiC",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_LUSC"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0002-1825-0090"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_MuSiC",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:MuSiC"
  },
  "description": "List of Cancer Driver Genes predicted by tool MuSiC in Lung Squamous Cell Carcinoma",
  "name": "Cancer Driver Genes in Lung Squamous Cell Carcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/3b75b24b-4618-48bb-89fd-1bcae54934d7",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_CHOL_OncodriveCLUST_OEBD002t000013.json
{
  "_id": "TCGA:2018-04-05_CHOL_P_OncodriveCLUST",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_CHOL"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0002-7218-2806"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_OncodriveCLUST",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:OncodriveCLUST"
  },
  "description": "List of Cancer Driver Genes predicted by tool OncodriveCLUST in Cholangiocarcinoma",
  "name": "Cancer Driver Genes in Cholangiocarcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/bea607fe-0d7e-4a7a-a839-84f5ba0ee4ff",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_PRAD_OncodriveFM_OEBD002t000050.json
{
  "_id": "TCGA:2018-04-05_PRAD_P_OncodriveFM",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_PRAD"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0001-7053-7717"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_OncodriveFM",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:OncodriveFM"
  },
  "description": "List of Cancer Driver Genes predicted by tool OncodriveFM in Prostate Adenocarcinoma",
  "name": "Cancer Driver Genes in Prostate Adenocarcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/12c99bfe-ec49-4c99-994a-1000a33280c9",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/reference_datasets/Dataset_Metrics_Ref_G_STD_Vertebrata.json
{
  "_id": "QfO:2011-07-07_G_STD_Vertebrata_M",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "QfO:2011-07-07_G_STD_Vertebrata"
  ],
  "community_ids": [
    "OEBC002"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0002-2170-853X",
    "orcid:0000-0002-9074-3507",
    "orcid:0000-0003-0019-1735",
    "orcid:0000-0002-9015-5588"
  ],
  "dates": {
    "creation": "2011-07-07T00:00:00Z",
    "modification": "2011-07-07T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "QfO:2011-07-07_I"
      }
    ]
  },
  "description": "Vertebrata Species Tree that can be used in the Generalized Species Tree Discordance benchmark as reference to assess the accuracy of orthologs predicted",
  "name": "Metrics Reference Dataset for Generalized Species Tree Discordance in Vertebrata benchmark",
  "type": "metrics_reference",
  "version": "unknown",
  "visibility": "community",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "http://orthology.benchmarkservice.org",
      "validations": [
        {
          "validation_stamp": "2011-07-07T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/reference_datasets/Dataset_Metrics_Ref_TreeFam-A.json
{
  "_id": "QfO:2011-07-07_TreeFam-A_M",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "QfO:2011-07-07_TreeFam-A"
  ],
  "community_ids": [
    "OEBC002"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0002-2170-853X",
    "orcid:0000-0002-9074-3507",
    "orcid:0000-0003-0019-1735",
    "orcid:0000-0002-9015-5588"
  ],
  "dates": {
    "creation": "2011-07-07T00:00:00Z",
    "modification": "2011-07-07T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "QfO:2011-07-07_I"
      }
    ]
  },
  "description": "Gene Tree that can be used in the TreeFam-A benchmark as reference to assess the accuracy of orthologs predicted",
  "name": "Metrics Reference Dataset for Agreement with Reference Gene Phylogenies: TreeFam-A benchmark",
  "type": "metrics_reference",
  "version": "unknown",
  "visibility": "community",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "http://www.treefam.org/",
      "validations": [
        {
          "validation_stamp": "2011-07-07T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_PRAD_MutSig2CV_OEBD002t00004X.json
{
  "_id": "TCGA:2018-04-05_PRAD_P_MutSig2CV",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_PRAD"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0001-7900-4239"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_MutSig2CV",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:MutSig2CV"
  },
  "description": "List of Cancer Driver Genes predicted by tool MutSig2CV in Prostate Adenocarcinoma",
  "name": "Cancer Driver Genes in Prostate Adenocarcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/2e8d4650-5498-4288-a461-23667ff553e2",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_BLCA_compositeDriver_OEBD002t00000A.json
{
  "_id": "TCGA:2018-04-05_BLCA_P_compositeDriver",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_BLCA"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0003-4526-9727"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_compositeDriver",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:compositeDriver"
  },
  "description": "List of Cancer Driver Genes predicted by tool compositeDriver in Bladder Urothelial Carcinoma",
  "name": "Cancer Driver Genes in Bladder Urothelial Carcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/bee64811-952a-4fac-b011-9cd28c0bd8d1",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/participant_datasets/Dataset_participant_LUSC_OncodriveCLUST_OEBD002t00003Z.json
{
  "_id": "TCGA:2018-04-05_LUSC_P_OncodriveCLUST",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Dataset",
  "challenge_ids": [
    "TCGA:2018-04-05_LUSC"
  ],
  "community_ids": [
    "OEBC001"
  ],
  "dataset_contact_ids": [
    "orcid:0000-0002-7218-2806"
  ],
  "participant_team_id": "TCGA:2018-04-05_team_OncodriveCLUST",
  "dates": {
    "creation": "2018-04-05T00:00:00Z",
    "modification": "2018-04-05T14:00:00Z"
  },
  "depends_on": {
    "rel_dataset_ids": [
      {
        "dataset_id": "TCGA:2018-04-05_input"
      }
    ],
    "tool_id": "TCGA:OncodriveCLUST"
  },
  "description": "List of Cancer Driver Genes predicted by tool OncodriveCLUST in Lung Squamous Cell Carcinoma",
  "name": "Cancer Driver Genes in Lung Squamous Cell Carcinoma",
  "type": "participant",
  "version": "unknown",
  "visibility": "public",
  "datalinks": [
    {
      "attrs": [
        "archive"
      ],
      "uri": "https://api.gdc.cancer.gov/data/bea607fe-0d7e-4a7a-a839-84f5ba0ee4ff",
      "validations": [
        {
          "validation_stamp": "2018-04-05T00:00:00Z",
          "status": "ok"
        }
      ]
    }
  ]
}
