=== inab/benchmarking-data-model/json-schemas/2.0.x/metrics.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/Metrics",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Metrics concept (OpenEBench Benchmarking Data Model schemas)",
	"description": "Abstract definition of any operation (implemented by a Tool) applied to a dataset",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares __canonical_id__, _metadata, __revision__, __license__",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of orig_id",
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$comment": "Declaration of references",
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$comment": "Declaration of links",
			"$ref": "_shared#/definitions/LinksProp"
		},
		{
			"$comment": "Declarations of name, description",
			"$ref": "_shared#/definitions/NameDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the metrics",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/MetricsTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/MetricsId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/Metrics" ]
		},
		
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The metrics original id"
		},
		
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The reference id(s) of this metrics (if any)"
		},
		
		"links": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksProp",
			"title": "Optional links related to the metrics"
		},
		
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Short metrics name"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Long metrics description, in Markdown format"
		},
		"keywords": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "List of keywords which match this metrics"
		},
		
		"metrics_contact_ids": {
			"title": "The contact id(s) of the creators of this metrics",
			"$ref": "_shared#/definitions/ReferredContactIds"
		},
		"formal_definition": {
			"title": "Formal definition of the metrics",
			"type": "string"
		},
		"representation_hints": {
			"title": "The optional representation hints which can be used or ignored by any data browser / viewer",
			"type": "object",
			"additionalProperties": true,
			"minProperties": 1
		}
	},
	"unevaluatedProperties": false,
	"required": ["_id","_schema","name","metrics_contact_ids"],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Metrics/QfO_metrics_TreeFam-A_precision.json
{
	"_id": "QfO:TreeFam-A_PPV",
	"_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Metrics",
	"name": "Positive Predictive Value rate for Reference Gene Phylogenies: TreeFam-A",
	"description": "Agreement (specificity) with Reference Gene Phylogenies - TreeFam-A measured through the Positive Predictive Value (PPV) rate",
	"metrics_contact_ids": ["orcid:0000-0002-2170-853X",
            "orcid:0000-0002-9074-3507",
            "orcid:0000-0003-0019-1735",
            "orcid:0000-0002-9015-5588"],
	"formal_definition": "PPV = TP / (TP + FP)",
	"references": [
		"doi:10.1093/bib/bbr034",
		"doi:10.1093/nar/gkj118"
	]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Metrics/QfO_metrics_TreeFam-A_recall.json
{
	"_id": "QfO:TreeFam-A_TPR",
	"_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Metrics",
	"name": "True Positives Rate for Reference Gene Phylogenies: TreeFam-A",
	"description": "Agreement (sensitivity) with Reference Gene Phylogenies - TreeFam-A measured through the True Positives Rate (TPR)",
	"metrics_contact_ids": ["orcid:0000-0002-2170-853X",
            "orcid:0000-0002-9074-3507",
            "orcid:0000-0003-0019-1735",
            "orcid:0000-0002-9015-5588"],
	"formal_definition": "TPR = TP / (TP + FN)",
	"references": [
		"doi:10.1093/bib/bbr034",
		"doi:10.1093/nar/gkj118"
	]
}
