=== inab/benchmarking-data-model/json-schemas/2.0.x/participant_team.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/ParticipantTeam",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "A team participating of one or more challenges concept (OpenEBench Benchmarking Data Model schemas 2.0)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares __canonical_id__, _metadata, __revision__, __license__",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of orig_id",
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$comment": "Declaration of references",
			"$ref": "_shared#/definitions/ReferencesProp"
		},
		{
			"$comment": "Declaration of links",
			"$ref": "_shared#/definitions/LinksProp"
		},
		{
			"$comment": "Declarations of name, description",
			"$ref": "_shared#/definitions/NameDescProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the participant team, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/ParticipantTeamTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/ParticipantTeamId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of '$id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/ParticipantTeam" ]
		},
		
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The participant team original id"
		},
		
		"references": {
			"$comment": "Placeholder covered by _shared#/definitions/ReferencesProp",
			"title": "The participant team reference id(s) (if any)"
		},
		
		"links": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksProp",
			"title": "Ways to contact the participant team responsible. It can be many different ones: public page, a social media link, some public chat, a public mailing list, ..."
		},
		
		"name": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Short participant team name (only valid within the scope of the benchmarking event)"
		},
		"description": {
			"$comment": "Placeholder covered by _shared#/definitions/NameDescProp",
			"title": "Optional, long description of the participant team, written in Markdown"
		},
		
		"benchmarking_event_id": {
			"title": "The parent benchmarking event where all the challenges where the team is going to participate",
			"minLength": 1,
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "BenchmarkingEvent",
					"members": [ "." ]
				}
			]
		},
		"enrolled_challenge_ids": {
			"description": "The challenges where this time has been enrolled",
			"type": "array",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"minLength": 1,
				"type": "string",
				"foreign_keys": [
					{
						"schema_id": "Challenge",
						"members": [ "." ]
					}
				]
			}
		},
		"tool_id": {
			"title": "The id of the tool used by the participants. It is optional (only required for engagement level 3), because there could be teams without their own public tools/implementations",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"team_members": {
			"title": "The members of the team, along their role(s)",
			"$ref": "_shared#/definitions/AuthorContactIds"
		},
		"team_manager_ids": {
			"title": "The managers of this team",
			"$ref": "_shared#/definitions/ReferredContactIds"
		}
	},
	"unevaluatedProperties": false,
	"required": [
		"_id",
		"_schema",
		"name",
		"benchmarking_event_id",
		"enrolled_challenge_ids",
		"team_members",
		"team_manager_ids"
	],
	"primary_key": ["_id"],
	"join_keys": [
		{
			"schema_id": "Challenge",
			"members": ["enrolled_challenge_ids", "benchmarking_event_id"],
			"refers_to": "BEChallengeIndex"
		}
	],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/participant_teams/team_OMA-Groups-2.0.json
{
  "_id": "QfO:2011-07-07_team_OMA-Groups-2.0",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/ParticipantTeam",
  "name": "OMA-Groups-2.0",
  "benchmarking_event_id": "OEBE0020000000",
  "enrolled_challenge_ids": [
    "QfO:2011-07-07_SwissTree",
    "QfO:2011-07-07_STD_Fungi",
    "QfO:2011-07-07_STD_Eukaryota",
    "QfO:2011-07-07_GOtest",
    "QfO:2011-07-07_TreeFam-A",
    "QfO:2011-07-07_G_STD_Fungi",
    "QfO:2011-07-07_G_STD_Eukaryota",
    "QfO:2011-07-07_G_STD_LUCA",
    "QfO:2011-07-07_G_STD_Vertebrata",
    "QfO:2011-07-07_ECtest"
  ],
  "tool_id": "QfO:OMA-Groups-2.0",
  "team_members": [
    {
      "person": "orcid:0000-0002-2170-853X",
      "roles": [
        "2451924d-425e-4778-9f4c-36c848ca70c2"
      ]
    }
  ],
  "team_manager_ids": [
    "orcid:0000-0002-2170-853X"
  ]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/participant_teams/team_OMA-GETHOGs.json
{
  "_id": "QfO:2011-07-07_team_OMA-GETHOGs",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/ParticipantTeam",
  "name": "OMA-GETHOGs",
  "benchmarking_event_id": "OEBE0020000000",
  "enrolled_challenge_ids": [
    "QfO:2011-07-07_SwissTree",
    "QfO:2011-07-07_STD_Fungi",
    "QfO:2011-07-07_STD_Eukaryota",
    "QfO:2011-07-07_GOtest",
    "QfO:2011-07-07_TreeFam-A",
    "QfO:2011-07-07_G_STD_Fungi",
    "QfO:2011-07-07_G_STD_Eukaryota",
    "QfO:2011-07-07_G_STD_LUCA",
    "QfO:2011-07-07_G_STD_Vertebrata",
    "QfO:2011-07-07_ECtest"
  ],
  "tool_id": "QfO:OMA-GETHOGs",
  "team_members": [
    {
      "person": "orcid:0000-0002-2170-853X",
      "roles": [
        "2451924d-425e-4778-9f4c-36c848ca70c2"
      ]
    }
  ],
  "team_manager_ids": [
    "orcid:0000-0002-2170-853X"
  ]
}
