=== inab/benchmarking-data-model/json-schemas/2.0.x/person.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/Person",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Person concept (OpenEBench Benchmarking Data Model schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares __canonical_id__, _metadata, __revision__, __license__",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of links",
			"$ref": "_shared#/definitions/LinksProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"$ref": "_shared#/definitions/PersonCanonicalId"
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of '$id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/Person" ]
		},
		
		"links": {
			"$comment": "Placeholder covered by _shared#/definitions/LinksProp",
			"title": "Optional links related to the contact"
		},
		
		"givenName": {
			"title": "First / given name",
			"type": "string",
			"minLength": 1
		},
		"surname": {
			"title": "Surname(s)",
			"type": "string",
			"minLength": 1
		},
		"email": {
			"title": "The e-mail address(es) of the contact",
			"type": "string",
			"minLength": 1,
			"format": "email"
		},
		"notes": {
			"title": "Comments about the contact",
			"type": "string"
		}
	},
	"unevaluatedProperties": false,
	"required": [
		"_id",
		"_schema",
		"email"
	],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/Persons/QfO_person4.json
{
	"_id": "orcid:0000-0003-0019-1735",
	"_schema": "https://w3id.org/openebench/scientific-schemas/2.0/Person",
	"givenName": "Toni",
	"surname": "Gabaldon",
	"email": "toni.gabaldon@crg.eu",
	"notes": "QfO4 organizer",
	"links": [
		{
			"label": "MainSite",
			"uri": "http://www.crg.eu/es/programmes-groups/comparative-genomics"
		},
		{
			"label": "SocialMedia",
			"comment": "ORCID",
			"uri": "https://orcid.org/0000-0003-0019-1735"
		}
	]
}
