=== inab/benchmarking-data-model/json-schemas/2.0.x/testAction.json
{
	"$id": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Test Action concept (OpenEBench Benchmarking Data Model schemas)",
	"$comment": "allOf and placeholders inspired by https://stackoverflow.com/a/24365393",
	"allOf": [
		{
			"$comment": "It declares _canonical_id, _metadata, _revision, _license, ___provenance___",
			"$ref": "_shared#/definitions/CommonKeys"
		},
		{
			"$comment": "Declaration of orig_id",
			"$ref": "_shared#/definitions/OrigIdProp"
		},
		{
			"$comment": "Declaration of anonymize",
			"$ref": "_shared#/definitions/AnonymizeProp"
		}
	],
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the test action, according to the rules",
			"type": "string",
			"oneOf": [
				{
					"$ref": "_shared#/definitions/OriginalIdOnSub"
				},
				{
					"$ref": "_shared#/definitions/TestActionTemporaryId"
				},
				{
					"$ref": "_shared#/definitions/TestActionId"
				}
			]
		},
		"_schema": {
			"title": "The JSON schema absolute URI. It must match the value of 'id' in the JSON schema",
			"type": "string",
			"format": "uri",
			"enum": [ "https://w3id.org/openebench/scientific-schemas/2.0/TestAction" ]
		},
		
		"orig_id": {
			"$comment": "Placeholder covered by _shared#/definitions/OrigIdProp",
			"title": "The test action original id"
		},
		
		"anonymize": {
			"$comment": "Placeholder covered by _shared#/definitions/AnonymizeProp",
			"title": "Anonymize rule for test actions"
		},
		
		"tool_id": {
			"title": "The id of the processing tool",
			"description": "The id of the tool which processes a set of datasets for this action. Most of the time is a participant's tool, but in the case of aggregation or statistic events, is a tool related to a kind of challenge's metrics",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Tool",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"action_type": {
			"title": "The type of action",
			"description": "The type of action performed by the tool, also describing the kind of input datasets.\nTest Event = Input + Tool -> Participant Data\nMetrics event = Participant Data + Metrics -> Assessment Data\nAggregation event = All Assessment Data + Metrics -> Aggregated Challenge Data\nParticipant Assessments event = Specific Participant Asssement Data + Metrics -> Participant Datasets Data\n",
			"type": "string",
			"enum": [
				"SetupEvent",
				"MetricsEvent",
				"StatisticsEvent",
				"ParticipantAssessmentsEvent",
				"AggregationEvent",
				"TestEvent"
			]
		},
		"involved_datasets": {
			"title": "The incoming, outgoing and settings datasets involved in this test action",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"dataset_id": {
						"title": "A received dataset, with this id",
						"type": "string",
						"foreign_keys": [
							{
								"schema_id": "Dataset",
								"members": [ "." ]
							}
						],
						"minLength": 1
					},
					"role": {
						"title": "The kind of dataset received for this action (report, metrics_reference, etc...)",
						"type": "string",
						"enum": [
							"incoming",
							"outgoing",
							"settings",
							"unknown"
						]
					},
					"received": {
						"title": "Reception date of the dataset (redundant, as the output dataset already has this date)",
						"type": "string",
						"format": "date-time"
					}
				},
				"additionalProperties": false,
				"required": [ "dataset_id", "role" ]
			}
		},
		"challenge_id": {
			"title": "The id of the challenge where this test action was generated",
			"type": "string",
			"foreign_keys": [
				{
					"schema_id": "Challenge",
					"members": [ "." ]
				}
			],
			"minLength": 1
		},
		"test_contact_ids": {
			"title": "Contact id(s) related to the action",
			"$ref": "_shared#/definitions/ReferredContactIds"
		},
		"status": {
			"title": "The lifecycle of the testAction will be managed by the API, validating it is progressing forward instead of backward",
			"type": "string",
			"enum": [
				"scheduled",
				"sent",
				"incomplete",
				"complete",
				"failed"
			]
		},
		"dates": {
			"title": "Relevant dates for this test action",
			"type": "object",
			"properties": {
				"creation": {
					"title": "Creation date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"modification": {
					"title": "Last modification date of the test action",
					"type": "string",
					"format": "date-time"
				},
				"public": {
					"title": "The date when this test action becomes public",
					"type": "string",
					"format": "date-time"
				}
			},
			"additionalProperties": false,
			"required": ["creation"]
		}
	},
	"unevaluatedProperties": false,
	"required": [
		"_id",
		"_schema",
		"involved_datasets",
		"challenge_id",
		"test_contact_ids",
		"dates"
	],
	"primary_key": ["_id"],
	"dependencies": {}
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/aggregation_events/AggregationEvent_SKCM_OEBA002t0000O2.json
{
    "_id": "TCGA:2018-04-05_SKCM_do_aggregation",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
    "action_type": "AggregationEvent",
    "challenge_id": "TCGA:2018-04-05_SKCM",
    "dates": {
        "creation": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_MutSig2CV",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_MutSig2CV",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_compositeDriver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_compositeDriver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_2020plus",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_2020plus",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_OncodriveFM",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_OncodriveFM",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_ActiveDriver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_ActiveDriver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_e-Driver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_e-Driver",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_OncodriveCLUST",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_OncodriveCLUST",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_TPR_MuSiC",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_A_precision_MuSiC",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_SKCM_Aggregation",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "orcid:0000-0003-4526-9727",
        "orcid:0000-0001-7900-4239",
        "orcid:0000-0003-1395-5378"
    ],
    "tool_id": "TCGA:aggregate_benchmark"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/TCGA/test_events/TestEvent_STAD_MutSig2CV_OEBA002t00005T.json
{
    "_id": "TCGA:2018-04-05_STAD_testEvent_MutSig2CV",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
    "action_type": "TestEvent",
    "challenge_id": "TCGA:2018-04-05_STAD",
    "dates": {
        "creation": "2018-04-05T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "TCGA:2018-04-05_input",
            "role": "incoming"
        },
        {
            "dataset_id": "TCGA:2018-04-05_STAD_P_MutSig2CV",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "orcid:0000-0003-4526-9727",
        "orcid:0000-0001-7900-4239",
        "orcid:0000-0003-1395-5378"
    ],
    "tool_id": "TCGA:MutSig2CV"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/CAMEO/TestActions/metrics/2017-01-14_00000021_1_metrics_lddt_server20.json
{
  "_id": "CAMEO:2017-01-14_00000021_1_metrics_iddt_server20",
  "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
  "action_type": "MetricsEvent",
  "challenge_id": "CAMEO:CAMEO-3D_2017-01-14",
  "tool_id": "CAMEO:server20",
  "involved_datasets": [
    {
      "dataset_id": "CAMEO:2017-01-14_00000021_1_M",
      "role": "incoming"
    },
    {
      "dataset_id": "CAMEO:2017-01-14_00000021_1_P_server20",
      "role": "incoming"
    },
    {
      "dataset_id": "CAMEO:2017-01-14_00000021_1_A_IDDT_server20",
      "role": "outgoing"
    }
  ],
  "dates": {
    "creation": "2017-01-14T05:30:00Z",
    "modification": "2017-01-14T05:45:00Z"
  },
  "test_contact_ids": ["orcid:0000-0002-6813-3200"]
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/metrics_events/MetricsEvent_G_STD_LUCA_OMA-Pairs_STD_comp_trees.json
{
    "_id": "QfO:2011-07-07_G_STD_LUCA_metricsEvent_OMA-Pairs_STD_comp_trees",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "QfO:2011-07-07_G_STD_LUCA",
    "dates": {
        "creation": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_G_STD_LUCA_M",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_OMA-Pairs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_G_STD_LUCA_A_STD_comp_trees_OMA-Pairs",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "tool_id": "QfO:OMA-Pairs"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/metrics_events/MetricsEvent_SwissTree_GETHOGs-2.0_SwissTree_TPR.json
{
    "_id": "QfO:2011-07-07_SwissTree_metricsEvent_GETHOGs-2.0_SwissTree_TPR",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
    "action_type": "MetricsEvent",
    "challenge_id": "QfO:2011-07-07_SwissTree",
    "dates": {
        "creation": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_SwissTree_M",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_P_GETHOGs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_SwissTree_A_SwissTree_TPR_GETHOGs-2.0",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "tool_id": "QfO:GETHOGs-2.0"
}

=== inab/benchmarking-data-model/prototype-data/2.0.x/QfO/aggregation_events/AggregationEvent_TreeFam-A.json
{
    "_id": "QfO:2011-07-07_TreeFam-A_do_aggregation",
    "_schema": "https://w3id.org/openebench/scientific-schemas/2.0/TestAction",
    "action_type": "AggregationEvent",
    "challenge_id": "QfO:2011-07-07_TreeFam-A",
    "dates": {
        "creation": "2011-07-07T00:00:00Z"
    },
    "involved_datasets": [
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_EggNOG",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_EggNOG",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_EggNOG-5-Fine-grained",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_EggNOG-5-Fine-grained",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_EggNOG-5-Groups",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_EggNOG-5-Groups",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_EnsemblCompara-e56",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_EnsemblCompara-e56",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_EnsemblCompara-e81",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_EnsemblCompara-e81",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_Hieranoid2",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_Hieranoid2",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_InParanoid",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_InParanoid",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_InParanoidCore",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_InParanoidCore",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OMA-GETHOGs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OMA-GETHOGs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_GETHOGs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_GETHOGs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OMA-Groups-RefSet5",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OMA-Groups-RefSet5",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OMA-Groups-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OMA-Groups-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OMA-Pairs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OMA-Pairs-2.0",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OrthoFinder-2.0-BLAST",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OrthoFinder-2.0-BLAST",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OrthoFinder-2.0-DIAMOND",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OrthoFinder-2.0-DIAMOND",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OrthoFinder-2.0-MSA",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OrthoFinder-2.0-MSA",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_PANTHER-LDO",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_PANTHER-LDO",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_PANTHER-all",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_PANTHER-all",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_RBH-BBH",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_RBH-BBH",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_RSD",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_RSD",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_SonicParanoid",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_SonicParanoid",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_SonicParanoid_fast",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_SonicParanoid_fast",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_SonicParanoid_sensitive",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_SonicParanoid_sensitive",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_MetaPhOrs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_MetaPhOrs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_Orthoinspector-1.30",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_Orthoinspector-1.30",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_PhylomeDB",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_PhylomeDB",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_TPR_OMA-Pairs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_A_TreeFam-A_PPV_OMA-Pairs",
            "role": "incoming"
        },
        {
            "dataset_id": "QfO:2011-07-07_TreeFam-A_Aggregation",
            "role": "outgoing"
        }
    ],
    "test_contact_ids": [
        "orcid:0000-0002-2170-853X",
        "orcid:0000-0002-9074-3507",
        "orcid:0000-0003-0019-1735",
        "orcid:0000-0002-9015-5588"
    ],
    "tool_id": "QfO:aggregate_benchmark"
}
